services:
  app:
    container_name: devflow-app
    build: .
    ports:
      - "3000:3000"
    env_file: .env
    environment:
      NODE_ENV: "production"
      AUTH_TRUST_HOST: "true"
    depends_on:
      - db
  db:
    image: postgres:17-alpine
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    container_name: devflow-db
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: devflow
volumes:
  pgdata:
